apiVersion: v1
kind: Service
metadata:
  name: clientcodefirst-service
  labels:
    app: clientcodefirst
spec:
  type: LoadBalancer  # Cambiado a NodePort o LoadBalancer para exponer la API
  ports:
    - port: 5091
      targetPort: 5091
  selector:
    app: clientcodefirst
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientcodefirst-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientcodefirst
  template:
    metadata:
      labels:
        app: clientcodefirst
    spec:
      containers:
        - name: clientcodefirst
          image: h2k2/clientcodefirst:2.0
          imagePullPolicy: Always
          env:
          - name: DBHOST
            value: mysql-service
          - name: MYSQL_USER
            value: userinfo
          - name: MYSQL_PASSWORD
            value: admin
          - name: MYSQL_DATABASE
            value: clientcodedb
          ports:
            - containerPort: 5091